apiVersion: v1
kind: Service
metadata:
  name: {{ include "full-stack-fastapi.fullname" . }}-backend
  labels:
    {{- include "full-stack-fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 8888
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.frontend.service.name }}
  selector:
    {{- include "full-stack-fastapi.selectorLabels" . | nindent 4 }}
